### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by ukkary** [Microsoft/react-popout-component#18]
using 

* react 16.2
* es2018

```
ReferenceError: window is not defined
at Object.set (/[somedir]//node_modules/react-popout-component/lib/globalContext.js:6:5)
at Object.<anonymous> (/[somedir]/node_modules/react-popout-component/lib/childWindowMonitor.js:28:15)
at Module._compile (module.js:635:30)
at Object.Module._extensions..js (module.js:646:10)
at Module.load (module.js:554:32)
at Function.Module._load (module.js:489:3)
at Module.require (module.js:579:17)
at require (internal/module.js:11:18)
at Object.<anonymous> ( /[somedir]/node_modules/react-popout-component/lib/Popout.js:19:1)
```

**Comment by prox07** [comment]
@ukkary can you go ahead and assign me this issue? I'm pretty sure that you are running the code within the ```windows script host```, hence no window object can be found.

**Comment by rexagod** [comment]
@ukkary  can you go ahead and assign me this issue? I'm pretty sure that you are running the code within the windows script host, hence no ```window object``` can be found.
